# Generated by Django 4.2.2 on 2023-07-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_author_user_quote_user_tag_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='tag of username',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
