# Generated by Django 4.2.2 on 2023-07-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_remove_tag_tag_of_username_remove_tag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.AlterField(
            model_name='author',
            name='born_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
